log    = /scratch/brianclark/gen2radiosims/trash/$(flavor)/step3.$(flavor).$(Process).log
output = /scratch/brianclark/gen2radiosims/trash/$(flavor)/step3.$(flavor).$(Process).out
error  = /scratch/brianclark/gen2radiosims/trash/$(flavor)/step3.$(flavor).$(Process).err

request_cpus = 1
request_memory = 3GB
request_disk = 5GB
Universe = vanilla
getenv = true
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

executable = step3_script.sh
arguments = $(step2dir) $(flavor)

queue
